# -*- coding: utf-8 -*-
"""run_all.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cvM9V4XJV_VAupQYuxxvxZLP91tWwcZw
"""

import subprocess

# Step 1: Run the model
subprocess.run(["python", "fraudulent_job_project.py"])

# Step 2: Start Streamlit dashboard
subprocess.run(["streamlit", "run", "fraud_dashboard.py"])